{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled -}}
---
kind: "ServiceMonitor"
apiVersion: {{ .Values.apiVersions.serviceMonitor | quote }}
metadata:
  name: {{ include "names.fullname" . | quote }}
  namespace: {{ include "names.namespace" . | quote }}
  labels:
    {{- include "labels.commonLabels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "labels.matchLabels" . | nindent 6 }}
  endpoints:
    {{- toYaml .Values.metrics.serviceMonitor.endpoints | nindent 4 }}
...
{{- end }}
